name = "sgr-blog"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "BLOG_CONTENT"
bucket_name = "sgr-blog-content"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTOR_INDEX"
index_name = "autorag-blog-deep"

